wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.19.8
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742292214
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 14
      - 23
      - 37
      4: 3.10.10
      5: 0.19.8
      8:
      - 5
      13: darwin-arm64
C:
  desc: null
  value: 1
class_weight:
  desc: null
  value: balanced
max_iter:
  desc: null
  value: 300
